version: '3.8'

networks:
  worker-dev-network:
    driver: bridge

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    ports:
      - "4000:8080"
      - "4001:8081"
    pull_policy: always
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - worker-dev-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    pull_policy: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - worker-dev-network
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    pull_policy: always
    networks:
      - worker-dev-network

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    pull_policy: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - worker-dev-network